[server]
hostname = "localhost"
offset = 0

[transport.http]
listener.port = 8080
listener.secured_port = 8043
#sender.ssl_profile.file_path = "conf/sslprofiles/senderprofiles.xml"
#sender.ssl_profile.read_interval = 600000

[management_api_basic_security_handler]
enable = true


[mediation]
# This will then override the synapse.properties file as defined in the header of the properties file
# This will allow using Saxon functions like `fn:matches($input, $pattern)`
synapse.enable_xpath_dom_failover = true

[[datasource]]
id = "BZ_DBReport_DS"
url = "jdbc:sqlserver://192.168.32.1:1444;databaseName=mi_dataservice"
username = "readonly"
password = "Flash8.2"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"